//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int DrugId { get; set; }
        public int Days { get; set; }
        public double Morning { get; set; }
        public double Noon { get; set; }
        public double Afternoon { get; set; }
        public double Night { get; set; }
        public double Quantity { get; set; }
        public string Note { get; set; }
        public int Cost { get; set; }
        public int SessionId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Session Session { get; set; }
    }
}
