//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndoscopyType
    {
        public EndoscopyType()
        {
            this.EndoscopyRecords = new HashSet<EndoscopyRecord>();
        }
    
        public int EndoScopyTypeId { get; set; }
        public string Name { get; set; }
        public string Pattern { get; set; }
    
        public virtual ICollection<EndoscopyRecord> EndoscopyRecords { get; set; }
    }
}
