//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndoscopyRecord
    {
        public EndoscopyRecord()
        {
            this.EndoscopyPhotoes = new HashSet<EndoscopyPhoto>();
        }
    
        public int EndoscopyRecordId { get; set; }
        public string Result { get; set; }
        public int EndoscopyTypeId { get; set; }
        public int SessionId { get; set; }
    
        public virtual ICollection<EndoscopyPhoto> EndoscopyPhotoes { get; set; }
        public virtual EndoscopyType EndoscopyType { get; set; }
        public virtual Session Session { get; set; }
    }
}
