//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESClinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsClinicEntities : DbContext
    {
        public EsClinicEntities()
            : base("name=EsClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClinicInfo> ClinicInfoes { get; set; }
        public DbSet<Diagnosis> Diagnoses { get; set; }
        public DbSet<Drug> Drugs { get; set; }
        public DbSet<EndoscopyPhoto> EndoscopyPhotoes { get; set; }
        public DbSet<EndoscopyRecord> EndoscopyRecords { get; set; }
        public DbSet<EndoscopyType> EndoscopyTypes { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Payor> Payors { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<Surcharge> Surcharges { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Visitor> Visitors { get; set; }
    }
}
