//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payor
    {
        public int PayorId { get; set; }
        public int SessionId { get; set; }
        public string Name { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
